CHANNEL = 't.me/test_channel_okoloboga'
DOG_CHANNEL = '@test_channel_okoloboga'
TELEGRAPH = 'https://telegra.ph/Example-08-18-2'
# CENTRAL_WALLET = 'UQDIkS1d_Lhd7EDttTtcmr9Xzg78uEMDEsYFde-PZCgfoOtU'
CENTRAL_WALLET = '0QDIkS1d_Lhd7EDttTtcmr9Xzg78uEMDEsYFde-PZCgfoFDe'
